cache:
    directories:
        - ~/.config/composer/

env:
    - JS_VERSION=5.1.0
    - JS_VERSION=^5.1

install:
    - composer global require phpunit/phpunit=^8
    - composer install
    - composer require justinrainbow/json-schema=$JS_VERSION

jobs:

    allow_failures:
        - php: nightly

    fast_finish: true

language: php

php:
    - 7.3
    - 7.4
    - nightly

script: phpunit
