env:
    - JS_VERSION=^4.1
    - JS_VERSION=^5.0

install:
    - composer install
    - composer require justinrainbow/json-schema=$JS_VERSION phpunit/phpunit=^5.0

language: php

matrix:

    allow_failures:
        - php: nightly

    fast_finish: true

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

script: vendor/bin/phpunit

sudo: false
