cache:
    directories:
        - ~/.config/composer/

env:
    - JS_VERSION=^4.1
    - JS_VERSION=^5.0

install:
    - composer global require phpunit/phpunit=^8
    - composer install
    - composer require justinrainbow/json-schema=$JS_VERSION phpunit/phpunit=^5.0

language: php

matrix:

    allow_failures:
        - php: nightly

    fast_finish: true

php:
    - 7.3
    - 7.4
    - nightly

script: vendor/bin/phpunit

sudo: false
